class EFX:
    Input = r"""/html/body/div[2]/div[2]/div[3]/div/div/div/div/div[3]/div[1]/div[1]/div/input"""
    PageF = r"""/html/body/div[2]/div[2]/div[3]/div/div/div/div/div[3]/table/tfoot/tr/td/div/div[3]/span[1]/button"""
    PageL = r"""/html/body/div[2]/div[2]/div[3]/div/div/div/div/div[3]/table/tfoot/tr/td/div/div[3]/span[2]/button"""
    PageN = r"""/html/body/div[2]/div[2]/div[3]/div/div/div/div/div[3]/table/tfoot/tr/td/div/div[3]/span[4]/button"""
    PageP = r"""/html/body/div[2]/div[2]/div[3]/div/div/div/div/div[3]/table/tfoot/tr/td/div/div[3]/span[5]/button"""
    Edit = r"""/html/body/div[2]/div[2]/div[3]/div/div/div/div/div[3]/div[2]/div/div/div/table/tbody/tr[1]/td[2]/div/button[1]"""
    Desc = r"""/html/body/div[2]/div[2]/div[3]/div/div/div/div/div[3]/div[2]/div/div/div/table/tbody/tr[1]/td[3]/div/div/div/div/button[2]"""
    D_Op = r"""//*[@id="description-autocomplete-adjustment-option-4"]"""
    Curr = r"""/html/body/div[2]/div[2]/div[3]/div/div/div/div/div[3]/div[2]/div/div/div/table/tbody/tr[1]/td[4]/div/div/div"""
    Option = r"""/html/body/div[8]/div[3]/ul/li[]"""
    Freq = r"""/html/body/div[2]/div[2]/div[3]/div/div/div/div/div[3]/div[2]/div/div/div/table/tbody/tr[1]/td[5]/div/div/div"""
    Year = r"""/html/body/div[2]/div[2]/div[3]/div/div/div/div/div[3]/div[2]/div/div/div/table/tbody/tr[1]/td[6]/div/div/div"""
    Quarter = r"""/html/body/div[2]/div[2]/div[3]/div/div/div/div/div[3]/div[2]/div/div/div/table/tbody/tr[1]/td[7]/div/div/div"""
    Month = r"""/html/body/div[2]/div[2]/div[3]/div/div/div/div/div[3]/div[2]/div/div/div/table/tbody/tr[1]/td[8]/div/div/div"""
    Add = r"""/html/body/div[2]/div[2]/div[3]/div/div/div/div/div[3]/div[1]/div[3]/div/div/span/button[3]"""
    Del = r"""/html/body/div[2]/div[2]/div[3]/div/div/div/div/div[3]/div[2]/div/div/div/table/tbody/tr[4]/td[2]/div/button[2]"""